spring:
  profiles:
    active: prod
  application:
    name: todo-app-webapp # the app will appear with this name in Eureka
  data:
    mongodb:
      #      host: mongodb # by default, mongodb is referred as localhost, but while it's in a container, localhost won't point to it, so the container's name should be given here
      host: localhost # use this when the app is used without Docker
  
logging:
  level:
    org.springframework: INFO
    com.todoapp.webapp.todoappwebapp: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: ./logs/todo-app-webapp_logs/

server:
    port: 8080